name: fast_trivia
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-63.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/

  uses-material-design: true
